const SECOND_MILLIS = 1000;

export const POLL_INTERVAL_MS = 30 * SECOND_MILLIS;
export const POLL_JITTER_PCT = 0.1;
export const MAX_CACHE_ENTRIES = 1000;

export const DEFAULT_INITIAL_CONFIG_REQUEST_RETRIES = 1;
export const DEFAULT_POLL_CONFIG_REQUEST_RETRIES = 7;
