const SECOND_MILLIS = 1000;
const MINUTE_MILLIS = 60 * SECOND_MILLIS;

export const POLL_INTERVAL_MILLIS = 5 * MINUTE_MILLIS;
export const JITTER_MILLIS = 30 * SECOND_MILLIS;
export const CACHE_TTL_MILLIS = 15 * MINUTE_MILLIS;
export const REQUEST_TIMEOUT_MILLIS = SECOND_MILLIS;

export const BASE_URL = 'https://eppo.cloud/api';
